Scroll when you send a DM
Hylozoic/hylo-redux pull request #184
Opened 2016-12-12 17:30 UTC by Connoropolous

regardless of whether you've scrolled up/back through the conversation or not

2016-12-12 21:31 UTC, levity commented on src/components/MessageSection.js
> +    const latestMessage = reverse(sortBy(this.props.messages || [], 'created_at'))[0]
rather than reversing the entire array to get the last item, let's just do `list[list.length - 1]`

2016-12-12 21:31 UTC, levity commented on src/components/MessageSection.js
> +    const latestMessage = reverse(sortBy(this.props.messages || [], 'created_at'))[0]
or `maxBy('created_at')`

2016-12-12 21:32 UTC, levity requested changes
make the suggested change to `latestMessage` and remove the `.swp` file that was checked in, & we're good

2016-12-12 23:20 UTC, Connoropolous commented on src/components/MessageSection.js
> +    const latestMessage = reverse(sortBy(this.props.messages || [], 'created_at'))[0]
K!

2016-12-13 20:50 UTC, Connoropolous commented
@levity changes made

2016-12-14 19:35 UTC, merged