Display popular skills on members page
Hylozoic/hylo-redux pull request #186
Opened 2016-12-15 02:21 UTC by robbiecarlton

Depends on https://github.com/Hylozoic/hylo-node/pull/197/files

2016-12-15 02:27 UTC, robbiecarlton commented
![screen shot 2016-12-14 at 7 27 03 pm](https://cloud.githubusercontent.com/assets/891124/21209754/65a879d6-c233-11e6-82d6-9711b0c5becd.png)
![screen shot 2016-12-14 at 7 27 21 pm](https://cloud.githubusercontent.com/assets/891124/21209755/65ac699c-c233-11e6-8cc2-ae1ade91bfd2.png)

2016-12-15 02:31 UTC, robbiecarlton commented
I think something that's missing here is highlighting the selected skill when it's being searched. I've asked Alex if she has any ideas about that.

2016-12-16 22:48 UTC, levity commented on src/containers/People.js
> +    popularSkills = popularSkills.map(skill => skill.replace('-', '‑'))
nice

2016-12-16 22:52 UTC, levity commented on src/containers/People.js
> +    var { popularSkills } = community
if you combine this and the next line as
```js
import { map } from 'lodash/fp'
const popularSkills = map(skill => skill.replace('-', '‑'), community.popularSkills)
```
then you won't have to create the empty array in the test. in general i think it's good to have the components be forgiving in what data they expect to receive.

2016-12-16 22:52 UTC, levity requested changes
Make the one suggested change and we're good

2016-12-16 23:38 UTC, merged