(WIP) Comment images
Hylozoic/hylo-redux pull request #247
Opened 2017-01-27 23:06 UTC by robbiecarlton

2017-01-30 23:37 UTC, robbiecarlton commented
Depends on https://github.com/Hylozoic/hylo-node/pull/212

2017-01-30 23:38 UTC, robbiecarlton commented
![screen shot 2017-01-30 at 3 46 56 pm](https://cloud.githubusercontent.com/assets/891124/22446538/88010b32-e70a-11e6-9f06-285326f21d9e.png)
![Uploading Screen Shot 2017-01-30 at 3.47.41 PM.png…]()
![screen shot 2017-01-30 at 3 48 23 pm](https://cloud.githubusercontent.com/assets/891124/22446540/8806c7ac-e70a-11e6-82d7-782b5f06de3c.png)
![screen shot 2017-01-30 at 3 49 15 pm](https://cloud.githubusercontent.com/assets/891124/22446539/8803f022-e70a-11e6-9bd8-6a047d66f0f4.png)
![Uploading Screen Shot 2017-01-30 at 4.35.57 PM.png…]()

2017-01-31 22:14 UTC, robbiecarlton commented
![screen shot 2017-01-31 at 3 13 28 pm](https://cloud.githubusercontent.com/assets/891124/22486740/f26c8aa6-e7c7-11e6-9408-5ee1fd175663.png)

2017-02-02 01:08 UTC, levity commented on src/components/CommentForm.js
> +          <CommentImageButton postId={postId} />
Let's put this behind a feature flag

2017-02-02 01:10 UTC, levity requested changes
Looks good to go once the feature flag is in place -- @lorenjohnson, do you want to skim over this and see if you have any opinions about style?

2017-02-02 01:10 UTC, lorenjohnson commented
Skimmin...

2017-02-02 01:11 UTC, levity commented on src/components/MessageForm.js
> +      <CommentImageButton postId={postId} />
this one too

2017-02-02 01:17 UTC, lorenjohnson commented on src/components/Comment.js
> +      : () => dispatch(showModal('image', {url: image.url}))
I'd personally prefer:
```javascript
showImage = () => {
  if (isMobile) {
    dispatch(navigate(`/image/${encodeUrl(image.url)}/${encodeUrl(location.pathname)}`))
  } else {
    dispatch(showModal('image', {url: image.url}))
  }
}
```
... or similar. I'm just not a fan of the ternary operator for multi-line anythings.

2017-02-02 01:23 UTC, lorenjohnson commented on src/components/CommentImageButton.js
> +  dispatch: React.PropTypes.func, currentUser: React.PropTypes.object
Do this above:
```javascript
import React, { PropTypes } from 'react'
```
and then here: 
```javascript
 dispatch: PropTypes.func, ...
```
I prefer that both to what you've done here and to fully resolving down to just "func".  Again, just my own opinions.

2017-02-02 01:25 UTC, lorenjohnson commented on src/components/CommentImageButton.js
> +export default CommentImageButton
You could also just do a:
```javascript
export default const CommentImageButton
```
above...

2017-02-02 01:36 UTC, lorenjohnson approved these changes
LGTM

2017-02-02 19:32 UTC, merged