No popovers on mobile
Hylozoic/hylo-redux pull request #272
Opened 2017-02-14 01:37 UTC by lorenjohnson

https://trello.com/c/cO2MOx5O

1) Carrying forward with my intent to bring up whatever I touch I went ahead and pod'ified App and added very basic render tests, as well as coverage for this ticket. 

2) Handling the blocking of mobile rendering of the popover in App where the popover is rendered rather than adding an isMobile to every call of handle / showPopover. 

    * Alternatively it seems like this could have been handled in popover reducer but I didn't see off-hand how to access isMobile in the state tree at the point of the popover reducer. Nor was I sure if that'd be idiomatic nor better than what I've done. Welcome to change it to any other way if there is a better way or a reason to not do it the way I've chosen.

2017-02-14 01:48 UTC, lorenjohnson commented on test/client/components/ShareTopicModal.test.js
> -import App from '../../../src/containers/App.js'
I am assuming this ".js" thing was a legacy thing and no longer necessary even in the server context? It of course breaks the App/index.js default thing relied upon for the pod.

2017-02-14 20:54 UTC, levity commented on test/client/components/ShareTopicModal.test.js
> -import App from '../../../src/containers/App.js'
yep

2017-02-14 20:58 UTC, levity requested changes
fix dispatch and you're good

2017-02-14 20:58 UTC, levity commented on src/containers/App/component.js
> +    const { dispatch } = this.context
App doesn't have dispatch in its context -- it's the component that puts it into context for everyone else -- you have to get it from props.

2017-02-14 21:01 UTC, lorenjohnson commented on src/containers/App/component.js
> +    const { dispatch } = this.context
I get that completely now, but for some reason I thought that Redux put dispatch into context for anything connected. My bad. Will fix.

2017-02-14 21:15 UTC, lorenjohnson commented on src/containers/App/component.js
> +    const { dispatch } = this.context
(It makes me very uneasy that non of our tests caught this issue... but the required PropType for dispatch will at least give us that warning once I put this right again.)

2017-02-15 00:26 UTC, levity approved these changes

2017-02-15 00:33 UTC, merged