[WIP] never let 'person is typing' message stay alive too long
Hylozoic/hylo-redux pull request #285
Opened 2017-02-27 21:53 UTC by Connoropolous

2017-02-28 23:21 UTC, levity commented on src/components/MessageForm/component.js
> +  }, 3000)
can you export `STARTED_TYPING_INTERVAL` from CommentForm and use it here?

2017-02-28 23:21 UTC, levity requested changes
Other than the duplicated constant, looks great

2017-02-28 23:23 UTC, Connoropolous commented
Yepp!

On Feb 28, 2017 6:21 PM, "Lawrence Wang" <notifications@github.com> wrote:

*@levity* commented on this pull request.
------------------------------

In src/components/MessageForm/component.js
<https://github.com/Hylozoic/hylo-redux/pull/285#discussion_r103576408>:

>    startTyping = throttle(() => {
     this.sendIsTyping(true)
-    if (this.queuedStop) clearTimeout(this.queuedStop)
-    this.queuedStop = setTimeout(() => this.sendIsTyping(false), 8000)
-  }, 5000)
+  }, 3000)

can you export STARTED_TYPING_INTERVAL from CommentForm and use it here?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/Hylozoic/hylo-redux/pull/285#pullrequestreview-24366678>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/ABWAYSfp8dan0uvRsKgCxCixl4IAx2kgks5rhKvdgaJpZM4MNrPZ>
.

2017-03-01 01:00 UTC, Connoropolous commented on src/components/PeopleTyping.js
> +const MS_CLEAR_TYPING = STARTED_TYPING_INTERVAL + 1000
@levity that made me think to import it here to and make this clear

2017-03-01 01:01 UTC, Connoropolous commented
should be good now

2017-03-01 01:30 UTC, levity commented on src/components/PeopleTyping.js
> +const MS_CLEAR_TYPING = STARTED_TYPING_INTERVAL + 1000
good call

2017-03-01 01:30 UTC, levity approved these changes

2017-03-01 04:33 UTC, merged